---
# defaults file for beacon

# docker network shared by the containers
shared_network_name: beacon-python

# postgres container and version
postgres_container_name: beacon-python-db
postgres_version: 13

# host port binding in docker CLI format
# use ip:port combination to bind on a specific network interface only
postgres_external_binding: 5432

# database access
postgres_user: beacon
postgres_pass: change_me!

# database to create and use
postgres_database_name: beacon

# the actual data will be mounted to the host OS in the specified directory
postgres_data_dir: /var/lib/postgresql/data

# directory to
postgres_init_dir: /var/lib/postgresql/init


# beacon-python container name and version
bp_container_name: beacon-python
bp_version: v1.9.1 

bp_config_dir: /etc/beacon

# external port binding for beacon API
bp_external_binding: 5050


# Name of the Beacon service
beacon_info_title: GA4GH Beacon at usegalaxy.eu 

# Documentation url for GA4GH Discovery
beacon_info_docs_url: https://app.swaggerhub.com/apis/ELIXIR-Finland/ga-4_gh_beacon_api_specification/1.0.0-rc1

# Globally unique identifier for this Beacon instance
beacon_info_beacon_id: galaxy.eu.beacon

# Description of this Beacon service
beacon_info_description: Beacon service hosting datastes from all over the usegalaxy.eu instance

# URL of Beacon service
beacon_info_url: https://usegalaxy.eu/beacon/

# Datetime when this Beacon was created
beacon_info_createtime: "2022-11-16T00:00:00Z"

# GA4GH Discovery type `groupId` and `artifactId`, joined in /service-info with apiVersion
# See https://github.com/ga4gh-discovery/ga4gh-service-info for more information and possible values
beacon_info_service_group: galaxy-eu
beacon_info_service_artifact: beacon

# GA4GH Discovery server environment, possible values: prod, dev, tes
beacon_info_environment: prod

#Globally unique identifier for organisation that hosts this Beacon service
beacon_info_org_id: usegalaxy.eu

# Name of organisation that hosts this Beacon service
beacon_info_org_name: Galaxy Europe

# Description for organisation
beacon_info_org_description: European Galaxy community

# Visit address of organisation
beacon_info_org_address: Georges-Köhler-Allee 79, 79110 Freiburg im Breisgau

# Homepage of organisation
beacon_info_org_welcome_url: https://galaxyproject.org/eu/

# URL for contacting organisation
beacon_info_org_contact_url: https://usegalaxy-eu.github.io/freiburg/people.html

# URL for organisation logo
beacon_info_org_logo_url: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png

# Other organisational information
beacon_info_org_info: The European Galaxy server UseGalaxy.eu is maintained primarily by the Freiburg Galaxy Team in collaboration with other academic groups across Europe and with the US Galaxy team.
