---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: CentOS-stream8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True

  - name: rocky9
    image: rockylinux/rockylinux:9 
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True

provisioner:
  name: ansible
#  inventory:
#  host_vars:
#    rocky9:
#      ansible_python_interpreter: "/ansible/bin/python"
verifier:
  name: ansible
