---
collections:
  - name: community.general
    version: 3.7.0
    source: https://galaxy.ansible.com
  - name: containers.podman
  - name: community.rabbitmq
    version: 1.1.0
  - name: ansible.posix
    version: 1.3.0

roles:
  - name: galaxyproject.nginx
    version: 0.7.0
  - name: usegalaxy_eu.certbot
    version: 0.1.5
  - name: usegalaxy_eu.rabbitmqserver
    version: 1.2.0
