---
- name: Remove guest user
  community.docker.docker_container_exec:
    container: "{{ rabbitmq_container.name }}"
    command: rabbitmqctl delete_user 'guest'
  ignore_errors: true

- name: Enable plugins
  community.docker.docker_container_exec:
    container: "{{ rabbitmq_container.name }}"
    command: "rabbitmq-plugins enable {{ item }}"
  loop: "{{ rabbitmq_plugins }}"
